select * from metprogram;

SELECT MET.MITROO,MET.EMAIL,METSTUPROG.PROGCODE FROM MET INNER JOIN METSTUPROG ON MET.MITROO = METSTUPROG.MITROO WHERE METSTUPROG.PROGCODE != 1 AND METSTUPROG.AK = 2016 ORDER BY 3;

SELECT MITROO,AK,PROGCODE,PERIOD FROM METKARTL WHERE AK = 2016 AND PROGCODE !=1 ORDER BY PROGCODE,PERIOD;




