
DELETE FROM TABLESN WHERE TABLENAME = 'METARDIPL';

SELECT MAX(ARDIPL) FROM METSTUPROG;
UPDATE TABLESN SET NEXTSN = 100 WHERE TABLENAME = 'METARDIPL';

INSERT INTO TABLESN (TABLENAME,NEXTSN) VALUES ('METARDIPL',NULL);
SELECT * FROM TABLESN WHERE TABLENAME = 'METARDIPL';
