CREATE TABLE METSYGR (K_SYGR VARCHAR(6) NOT NULL, TMIMACODE INTEGER NOT NULL, TOMCDDE INTEGER, TITLOS VARCHAR(100), K_EKD VARCHAR(4), AK_EKD INTEGER, TOPOS_EKD VARCHAR(100));
CREATE UNIQUE INDEX METSYGR_IDX  ON METSYGR (K_SYGR,TMIMACODE);
CREATE TABLE METSYGRAMA (K_SYGR VARCHAR(6) NOT NULL, TMIMACODE INTEGER NOT NULL, COURCODE INTEGER NOT NULL, AK INTEGER NOT NULL);
CREATE UNIQUE INDEX METSYGRAMA_IDX ON METSYGRAMA (K_SYGR,TMIMACODE, COURCODE, AK);

