ALTER TABLE METSTUPROG ADD CODESYN REAL;

SELECT MITROO||PROGCODE||TMIMACODE||CODESYN FROM METDSYNERG GROUP BY 1 HAVING COUNT(MITROO||PROGCODE||TMIMACODE||CODESYN ) >1;

ALTER TABLE METSTUPROG ADD TMIMACODE INTEGER;

UPDATE METSTUPROG SET TMIMACODE = ;

UPDATE METSTUPROG SET CODESYN = (SELECT CODESYN FROM METDSYNERG WHERE METSTUPROG.MITROO = METDSYNERG.MITROO AND METSTUPROG.PROGCODE = METDSYNERG.PROGCODE
		AND METSTUPROG.TMIMACODE = METDSYNERG.TMIMACODE)  WHERE MITROO||PROGCODE||TMIMACODE IN (SELECT MITROO||PROGCODE||TMIMACODE FROM METDSYNERG);

SELECT PROGCODE||MITROO||TMIMACODE FROM METSTUPROG GROUP BY 1 HAVING COUNT(PROGCODE||MITROO||TMIMACODE)>1;

DELETE FROM TABLESN WHERE TABLENAME = 'METANATHESI';

SELECT MAX(CODESYN) FROM METANATHESI;

UPDATE TABLESN SET TABLENAME='METANATHESI',NEXTSN= WHERE TABLENAME ='METDSYNERG';

CREATE UNIQUE INDEX TABLESN_IDX ON TABLESN (TABLENAME);
