CREATE TABLE METPARATASI(MITROO VARCHAR(8) NOT NULL, PROGCODE INTEGER NOT NULL,TMIMACODE INTEGER NOT NULL, SEGNO SMALLINT NOT NULL, DATEAPO DATE NOT NULL, DATEEOS DATE NOT NULL, GSDATE DATE,AITIOLOGIA VARCHAR(80));
CREATE UNIQUE INDEX METPARAT_IDX  ON METPARATASI (MITROO,PROGCODE,TMIMACODE,SEGNO);


