DROP TRIGGER MET_DEL;
DROP TRIGGER MET_INS;
DROP TRIGGER MET_UPDT;
DROP TRIGGER MET_INS_SN;

ALTER TABLE MET          MODIFY EMAIL VARCHAR(50);
ALTER TABLE MET_IST   MODIFY EMAIL VARCHAR(50);
ALTER TABLE MET_WEB MODIFY EMAIL VARCHAR(50);

ALTER TABLE MET_IST ADD ERASMUS    		VARCHAR(1);
ALTER TABLE MET_IST ADD DIPLEPVN    		VARCHAR(40);
ALTER TABLE MET_IST ADD DIPLONOMA 		VARCHAR(30);
ALTER TABLE MET_IST ADD DIPLPATR    		VARCHAR(30);
ALTER TABLE MET_IST ADD PARAVOLO    	VARCHAR(1);
ALTER TABLE MET_IST ADD MHXANIK    		VARCHAR(1);
ALTER TABLE MET_IST ADD WORK    		VARCHAR(1);
ALTER TABLE MET_IST ADD DIMOSKINOT 	INTEGER;
ALTER TABLE MET_IST ADD XU    			VARCHAR(1);
ALTER TABLE MET_IST ADD OFEILES    		VARCHAR(10);

ALTER TABLE MET_WEB ADD ERASMUS    	VARCHAR(1);
ALTER TABLE MET_WEB ADD DIPLEPVN    	VARCHAR(40);
ALTER TABLE MET_WEB ADD DIPLONOMA 	VARCHAR(30);
ALTER TABLE MET_WEB ADD DIPLPATR    	VARCHAR(30);
ALTER TABLE MET_WEB ADD PARAVOLO   	VARCHAR(1);
ALTER TABLE MET_WEB ADD MHXANIK    		VARCHAR(1);
ALTER TABLE MET_WEB ADD WORK   		VARCHAR(1);
ALTER TABLE MET_WEB ADD DIMOSKINOT 	INTEGER;
ALTER TABLE MET_WEB ADD XU   			VARCHAR(1);
ALTER TABLE MET_WEB ADD OFEILES   		VARCHAR(10);

ERASE MET_PROC;

STORE  MET_PROC
PROCEDURE: MET_PROC STATIC
 	PARAMETERS
   		String   	 	: sMODIFTYPE
   		String    		: sMITROO
   		Number 		: nTMIMACODE
   		String    		: sAR_T
   		String    		: sEPVN
   		String    		: sONOMA
   		String    		: sPATR
   		String    		: sMHTR
   		String    		: sSEX
   		String    		: sYPHK
   		String    		: sXU
   		String    		: sCOORIG
   		String    		: sNOMOSORIG
  		String    		: sPOLIORIG
   		Date/Time 	: dBIRTHDATE
   		String    		: sNOMOSMHTR
   		String    		: sPOLIMHTR
   		Number		: nDIMOSKINOT
   		String	    	: sDIMOTOLOGIO
   		String 	   	: sCOKAT
   		String  	  	: sNOMOSKAT
   		String   	 	: sPOLIKAT
  		String   	 	: sPERIOXI
   		String   	 	: sODOS
   		String   	 	: sTT
   		String   	 	: sTEL1
   		String   	 	: sTEL2
   		String   	 	: sEMAIL
		String   	 	: sWORK
		String   	 	: sMHXANIK
		String   	 	: sOFEILES
		String   	 	: sDIPLEPVN
		String   	 	: sDIPLONOMA
		String   	 	: sDIPLPATR
		String   	 	: sPARAVOLO
		String   	 	: sUSRNAME
		String   	 	: sERASMUS
 	LOCAL VARIABLES
   		SQL HANDLE: hSql1
   		SQL HANDLE: hSql2
 	ACTIONS
   		On Procedure Startup
    			Call SqlConnect( hSql1 )
    			Call SqlConnect( hSql2 )
   		On Procedure Execute
			Call SqlPrepare( hSql1 , 'INSERT INTO MET_WEB(
										DATEMODIF, MODIFTYPE, MITROO, TMIMACODE, AR_T, EPVN, ONOMA, PATR, MHTR, SEX, YPHK, XU, COORIG, NOMOSORIG, 
										POLIORIG, BIRTHDATE, NOMOSMHTR, POLIMHTR, DIMOSKINOT, DIMOTOLOGIO, COKAT, NOMOSKAT, POLIKAT, PERIOXI, ODOS, TT, TEL1, 
										TEL2, EMAIL, WORK, MHXANIK, OFEILES, DIPLEPVN, DIPLONOMA, DIPLPATR, PARAVOLO, USRNAME, ERASMUS)
     							      	       VALUES(
										SYSDATETIME, :sMODIFTYPE, :sMITROO, :nTMIMACODE, :sAR_T, :sEPVN, :sONOMA, :sPATR, :sMHTR, :sSEX, :sYPHK, :sXU, :sCOORIG, :sNOMOSORIG,
										:sPOLIORIG, :dBIRTHDATE, :sNOMOSMHTR, :sPOLIMHTR,  :nDIMOSKINOT, :sDIMOTOLOGIO, :sCOKAT, :sNOMOSKAT, :sPOLIKAT, :sPERIOXI, :sODOS, :sTT, :sTEL1,
										:sTEL2, :sEMAIL,  :sWORK, :sMHXANIK, :sOFEILES, :sDIPLEPVN, :sDIPLONOMA, :sDIPLPATR, :sPARAVOLO, :sUSRNAME, :sERASMUS)' )
    			Call SqlExecute( hSql1 )
    			Call SqlPrepare( hSql2 , 'INSERT INTO MET_IST(
										USERNAME, DATEMODIF, MODIFTYPE, MITROO, TMIMACODE, AR_T, EPVN, ONOMA, PATR, MHTR, SEX, YPHK, XU, COORIG, NOMOSORIG, 
										 POLIORIG, BIRTHDATE, NOMOSMHTR, POLIMHTR, DIMOSKINOT, DIMOTOLOGIO, COKAT, NOMOSKAT, POLIKAT, PERIOXI, ODOS, TT, TEL1, 
										TEL2, EMAIL, WORK, MHXANIK,  OFEILES, DIPLEPVN, DIPLONOMA, DIPLPATR, PARAVOLO, USRNAME, ERASMUS)
     							               VALUES(
										USER, SYSDATETIME, :sMODIFTYPE, :sMITROO, :nTMIMACODE, :sAR_T, :sEPVN, :sONOMA, :sPATR, :sMHTR, :sSEX, :sYPHK, :sXU, :sCOORIG, :sNOMOSORIG,
										:sPOLIORIG, :dBIRTHDATE, :sNOMOSMHTR, :sPOLIMHTR, :nDIMOSKINOT, :sDIMOTOLOGIO, :sCOKAT, :sNOMOSKAT, :sPOLIKAT, :sPERIOXI, :sODOS, :sTT, :sTEL1,
										:sTEL2, :sEMAIL,  :sWORK, :sMHXANIK, :sOFEILES, :sDIPLEPVN, :sDIPLONOMA, :sDIPLPATR, :sPARAVOLO, :sUSRNAME, :sERASMUS)' )
    			Call SqlExecute( hSql2 )
   		On Procedure Close
    			Call SqlDisconnect( hSql1 )
    			Call SqlDisconnect( hSql2 );


CREATE TRIGGER SYSADM.MET_INS AFTER INSERT ON MET
	( EXECUTE MET_PROC (
				'i', MET.MITROO, MET.TMIMACODE, MET.AR_T, MET.EPVN, MET.ONOMA, MET.PATR, MET.MHTR, MET.SEX, MET.YPHK, MET.XU, MET.COORIG, MET.NOMOSORIG, 
				MET.POLIORIG, MET.BIRTHDATE, MET.NOMOSMHTR, MET.POLIMHTR, MET.DIMOSKINOT, MET.DIMOTOLOGIO, MET.COKAT, MET.NOMOSKAT, MET.POLIKAT, MET.PERIOXI, MET.ODOS, MET.TT, MET.TEL1, 
				MET.TEL2, MET.EMAIL, MET.WORK, MET.MHXANIK, MET.OFEILES,  MET.DIPLEPVN, MET.DIPLONOMA, MET.DIPLPATR, MET.PARAVOLO, MET.USRNAME, MET.ERASMUS) )
FOR EACH ROW;


CREATE TRIGGER SYSADM.MET_DEL AFTER DELETE ON MET
	( EXECUTE MET_PROC (
				'd', MET.MITROO, MET.TMIMACODE, MET.AR_T, MET.EPVN, MET.ONOMA, MET.PATR, MET.MHTR, MET.SEX, MET.YPHK, MET.XU, MET.COORIG, MET.NOMOSORIG, 
				MET.POLIORIG, MET.BIRTHDATE, MET.NOMOSMHTR, MET.POLIMHTR, MET.DIMOSKINOT, MET.DIMOTOLOGIO, MET.COKAT, MET.NOMOSKAT, MET.POLIKAT, MET.PERIOXI, MET.ODOS, MET.TT, MET.TEL1, 
				MET.TEL2, MET.EMAIL, MET.WORK, MET.MHXANIK, MET.OFEILES,  MET.DIPLEPVN, MET.DIPLONOMA, MET.DIPLPATR, MET.PARAVOLO, MET.USRNAME, MET.ERASMUS) )
FOR EACH ROW;


CREATE TRIGGER SYSADM.MET_UPDT AFTER UPDATE ON MET REFERENCING OLD AS OLD_MET NEW AS NEW_MET
  	( EXECUTE MET_PROC (
				'u', MET.MITROO, MET.TMIMACODE, MET.AR_T, MET.EPVN, MET.ONOMA, MET.PATR, MET.MHTR, MET.SEX, MET.YPHK, MET.XU, MET.COORIG, MET.NOMOSORIG, 
				MET.POLIORIG, MET.BIRTHDATE, MET.NOMOSMHTR, MET.POLIMHTR, MET.DIMOSKINOT, MET.DIMOTOLOGIO, MET.COKAT, MET.NOMOSKAT, MET.POLIKAT, MET.PERIOXI, MET.ODOS, MET.TT, MET.TEL1, 
				MET.TEL2, MET.EMAIL, MET.WORK, MET.MHXANIK, MET.OFEILES,  MET.DIPLEPVN, MET.DIPLONOMA, MET.DIPLPATR, MET.PARAVOLO, MET.USRNAME, MET.ERASMUS) )
FOR EACH ROW;

