SELECT MITROO||' '||PROGCODE FROM METSTUPROG GROUP BY 1 HAVING COUNT (MITROO||PROGCODE)>1;

SELECT CODESYN||' '||MITROO||' '||PROGCODE||' '||TMIMACODE FROM METDSYNERG GROUP BY 1 HAVING COUNT(CODESYN||MITROO||PROGCODE||TMIMACODE) >1; 

SELECT CODESYN||' '||DATEANATH||' '||TMIMACODE FROM METANATHESI GROUP BY 1 HAVING COUNT(CODESYN||DATEANATH||' '||TMIMACODE)>1;

ALTER TABLE METSTUPROG ADD DATEANAG DATE;

CREATE TABLE METDSYNERGTEMP ( MITROO VARCHAR (8)  NOT NULL, PROGCODE INTEGER,DATEANAG DATE) PCTFREE 10;

INSERT INTO METDSYNERGTEMP SELECT DISTINCT METDSYNERG.MITROO,METDSYNERG.PROGCODE,DATEANAG
    FROM METDSYNERG,METANATHESI
    WHERE METANATHESI.CODESYN=METDSYNERG.CODESYN AND METANATHESI.TMIMACODE = METDSYNERG.TMIMACODE AND DATEANAG IS NOT NULL;

SELECT MITROO||' '||PROGCODE FROM METDSYNERGTEMP GROUP BY 1 HAVING COUNT(MITROO||PROGCODE)>1;

UPDATE METSTUPROG SET DATEANAG = 
    (SELECT DATEANAG FROM METDSYNERGTEMP WHERE METSTUPROG.MITROO = METDSYNERGTEMP.MITROO 
     AND METSTUPROG.PROGCODE = METDSYNERGTEMP.PROGCODE) WHERE MITROO||PROGCODE  IN (SELECT MITROO||PROGCODE FROM METDSYNERGTEMP);

DROP TABLE METDSYNERGTEMP;

.SOS Για ασφάλεια να μείνει προσωρινά η παρακάτω κολόνα !!! SOS;

ALTER TABLE METANATHESI DROP DATEANAG;
