  1. Δημιουργία πίνακα METPROGAT;
  
  CREATE TABLE METPROGAT (
  TMIMACODE INTEGER NOT NULL, 
  PROGCODE INTEGER NOT NULL, 
  AK INTEGER NOT NULL,
  LIMIT DOUBLE PRECISION, 
  LIMITDIPL DOUBLE PRECISION, 
  ROUNDMO VARCHAR(1), 
  WDIPL DOUBLE PRECISION, 
  ARCOURDIPL INTEGER);

  2. Δημιουργία INDEX METPROGAT_IDX;

  CREATE UNIQUE INDEX METPROGAT_IDX ON METPROGAT(
  TMIMACODE, 
  PROGCODE, 
  AK);

  3. Ενημέρωση του πίνακα METPROGAT με τις αντίστοιχες τιμές του METPROGRAM;

   INSERT INTO METPROGAT SELECT TMIMACODE,PROGCODE,2004,LIMIT,LIMITDIPL,ROUNDMO,WDIPL,ARCOURDIPL FROM METPROGRAM;
   INSERT INTO METPROGAT SELECT TMIMACODE,PROGCODE,2003,LIMIT,LIMITDIPL,ROUNDMO,WDIPL,ARCOURDIPL FROM METPROGRAM;
   INSERT INTO METPROGAT SELECT TMIMACODE,PROGCODE,2002,LIMIT,LIMITDIPL,ROUNDMO,WDIPL,ARCOURDIPL FROM METPROGRAM;
   INSERT INTO METPROGAT SELECT TMIMACODE,PROGCODE,2001,LIMIT,LIMITDIPL,ROUNDMO,WDIPL,ARCOURDIPL FROM METPROGRAM;
   INSERT INTO METPROGAT SELECT TMIMACODE,PROGCODE,2000,LIMIT,LIMITDIPL,ROUNDMO,WDIPL,ARCOURDIPL FROM METPROGRAM;

  4. Διαγραφή των κολονών του πίνακα METPOGRAM που σχετίζονται με τον πίνακα METPROGAT;

  ALTER TABLE METPROGRAM DROP LIMIT,LIMITDIPL,ROUNDMO,WDIPL,ARCOURDIPL;

  5. Προσθήκη νέων κολονών στον πίνακα metprogat από τον πίνακα metprogram;

  ALTER TABLE METPROGAT ADD MINI VARCHAR(15),MAXI VARCHAR(15),LECTPER VARCHAR(10),YPAPOF VARCHAR(50);

  6. Ενημέρωση των κολονών από τις αντίστοιχες κολόνες του metprogram;

  UPDATE METPROGAT SET MINI = (SELECT MINI FROM METPROGRAM WHERE METPROGAT.PROGCODE = METPROGRAM.PROGCODE);
  UPDATE METPROGAT SET MAXI = (SELECT MAXI FROM METPROGRAM WHERE METPROGAT.PROGCODE = METPROGRAM.PROGCODE);
  UPDATE METPROGAT SET LECTPER = (SELECT LECTPER FROM METPROGRAM WHERE METPROGAT.PROGCODE = METPROGRAM.PROGCODE);
  UPDATE METPROGAT SET YPAPOF = (SELECT YPAPOF FROM METPROGRAM WHERE METPROGAT.PROGCODE = METPROGRAM.PROGCODE);

  7. Διαγραφή των κολονών του πίνακα METPOGRAM που σχετίζονται με τον πίνακα METPROGAT;

 ALTER TABLE METPROGRAM DROP MINI,MAXI,LECTPER,YPAPOF;
