CREATE TABLE METWEBAITEGR (TMIMACODE INTEGER NOT NULL, PROGCODE INTEGER NOT NULL, MITROO VARCHAR(8) NOT NULL, 
                                                   AK INTEGER, PERIOD VARCHAR(2), DATEEGR DATE, AP VARCHAR(100), DTARR DATE, STATUS SMALLINT, REPLY VARCHAR(200));

CREATE UNIQUE INDEX METWEBAITEGR ON METWEBAITEGR(TMIMACODE, PROGCODE, MITROO);

ALTER TABLE METWEBAITEGR PRIMARY KEY (TMIMACODE, PROGCODE, MITROO);

CREATE PUBLIC  SYNONYM METWEBAITEGR FOR SYSADM.METWEBAITEGR;


GRANT DELETE ON  METWEBAITEGR  TO MPAPAKYR;

GRANT INSERT ON  METWEBAITEGR  TO MPAPAKYR;

GRANT SELECT ON  METWEBAITEGR  TO MPAPAKYR;

GRANT UPDATE ON  METWEBAITEGR  TO MPAPAKYR;



CREATE TABLE METWEBAITKARTL (TMIMACODE INTEGER NOT NULL, PROGCODE INTEGER NOT NULL, MITROO VARCHAR(8) NOT NULL, 
                                                   AK INTEGER, PERIOD VARCHAR(2), COURCODE INTEGER NOT NULL,  STATUS SMALLINT, REPLY VARCHAR(200));

CREATE UNIQUE INDEX METWEBAITKARTL ON METWEBAITKARTL(TMIMACODE, PROGCODE, MITROO, COURCODE);

ALTER TABLE METWEBAITKARTL PRIMARY KEY (TMIMACODE, PROGCODE, MITROO,COURCODE);

CREATE PUBLIC  SYNONYM METWEBAITKARTL FOR SYSADM.METWEBAITKARTL;

GRANT DELETE ON  METWEBAITKARTL  TO MPAPAKYR;

GRANT INSERT ON  METWEBAITKARTL TO MPAPAKYR;

GRANT SELECT ON  METWEBAITKARTL TO MPAPAKYR;

GRANT UPDATE ON  METWEBAITKARTL TO MPAPAKYR;

