SELECT  COUNT(METDSYNERG.MITROO)
FROM METDIPLGRADE,METDSYNERG,METSTUPROG
WHERE  METDSYNERG.CODESYN = METDIPLGRADE.CODESYN AND METDSYNERG.TMIMACODE = 3 AND METDSYNERG.PROGCODE = 1
AND METDIPLGRADE.TYPEDEP = 1 AND METDIPLGRADE.DATEDEL IS NULL 
AND METSTUPROG.MITROO = METDSYNERG.MITROO AND METSTUPROG.MITROO = METDSYNERG.MITROO AND METSTUPROG.PROGCODE = METDSYNERG.PROGCODE
AND METDIPLGRADE.DEPCODE = 30050 AND METSTUPROG.DATEANAG IS NULL 
AND METDSYNERG.MITROO NOT IN (SELECT MITROO FROM METDIAKOP WHERE PROGCODE =1 AND DATEAPO<=SYSDATE AND (DATEEOS IS NULL OR DATEEOS > SYSDATE))
AND @MID(METDIPLGRADE.DATEINS,0,4) < @MID(SYSDATE,0,4);






