CREATE TABLE METOBLISTUD (
  MITROO VARCHAR(8) NOT NULL, 
  K_TM INTEGER NOT NULL, 
  PROGCODE INTEGER NOT NULL,
  COURCODE INTEGER NOT NULL, 
  PERIOD VARCHAR(2),
  OMADA VARCHAR(4), 
  AK INTEGER, 
  H_XREW DATE);

CREATE UNIQUE INDEX METOBLISTUD_IDX ON METOBLISTUD(
  MITROO, 
  K_TM, 
  PROGCODE,
  COURCODE);

CREATE TABLE METOBLISTU (
  MITROO VARCHAR(8) NOT NULL, 
  K_TM INTEGER NOT NULL, 
  PROGCODE INTEGER NOT NULL,
  PERIOD VARCHAR(2) NOT NULL, 
  TOTEPIL INTEGER, 
  OMADA VARCHAR(4));

CREATE UNIQUE INDEX METOBLISTU_IDX ON METOBLISTU(
  MITROO,
  K_TM, 
  PROGCODE,
  PERIOD);
