;ELEGXO AN YPARXEI YPOPSIFIOS DIDAKTORAS XORIS KATAXORIMENO FYLO;
SELECT MET.MITROO
FROM MET,METSTUPROG
WHERE METSTUPROG.PROGCODE =1
	AND MET.MITROO = METSTUPROG.MITROO AND SEX IS NULL;


;THELEI PARAMETRO TO ETOS (BALE 2015);

SELECT SEX, COUNT(MET.MITROO)
FROM MET,METSTUPROG
WHERE METSTUPROG.PROGCODE = 1
	AND MET.MITROO = METSTUPROG.MITROO AND SEX IS NOT NULL
	AND (METSTUPROG.DATEANAG IS NULL OR METSTUPROG.DATEANAG >= '01-MAR-'||:1) 
	AND METSTUPROG.MITROO NOT IN (SELECT MITROO FROM METDIAKOP WHERE PROGCODE = 1 AND DATEAPO <  '01-MAR-'||:1 AND DATEEOS IS NULL)
GROUP BY 1 ORDER BY 1;

SELECT MET.MITROO,MET.EPVN,MET.ONOMA,SEX,METSTUPROG.AK
FROM MET,METSTUPROG
WHERE METSTUPROG.PROGCODE = 1
	AND MET.MITROO = METSTUPROG.MITROO AND SEX IS NOT NULL
	AND (METSTUPROG.DATEANAG IS NULL OR METSTUPROG.DATEANAG >= '01-MAR-'||:1) 
	AND METSTUPROG.MITROO NOT IN (SELECT MITROO FROM METDIAKOP WHERE PROGCODE = 1 AND DATEAPO <  '01-MAR-'||:1 AND DATEEOS IS NULL)
ORDER BY METSTUPROG.AK,EPVN,ONOMA;
