;====================================================================================================;
;PROPTYXIAKOI FOITHTES ANA ETOS SPOUDON, ETOS PROTHS EGGRAFHS, FYLO KAI YPHKOOTHTA;
;TO QUERY EXEI KAI MIA PARAMETRO POU PREPEI NA BALETE KAI EINAI O KODIKOS THS SXOLHS;
;====================================================================================================;


SELECT  COUNT(ST_F.K_F),  ST_F.AK AS ETOS_A_EGRAFHS,EGRAFI.AK AS AK,SEX AS FYLO,pltab.pltext AS XORA
FROM ST_F , PLTAB, EGRAFI
where st_f.k_f  NOT IN (SELECT K_F FROM HST_F WHERE ETOSDIPL <= :1  ) AND ST_F.K_F = EGRAFI.K_F AND EGRAFI.AK = :1
and ST_F.k_f not in (select k_f from apofoit  WHERE AK <= :1) and YPHK != '0099' 
AND PLTAB.PLCODE = YPHK AND PLTAB.PLCOLUMN = 'YPHK'
and ST_F.k_f not in (select k_f from diagrafentes  WHERE AK <= :1) and sex is not null
and ST_F.k_f not in (select k_f from st_f where stustatus = 'DI' ) 
AND ST_F.AK IS NOT NULL  AND ST_F.AK <= :1 GROUP BY 2,3,4,5
ORDER BY 5;

;====================================================================================================;
;FOITHTES ANA EPIPEDO SPOYDON (MDE - YD), ETOS SPOUDON, FYLO YPHKOOTHTA.


;TO QUERY EXEI KAI MIA PARAMETRO POU PREPEI NA BALETE KAI EINAI O KODIKOS THS SXOLHS;
;====================================================================================================;

SELECT COUNT(MET.MITROO) AS SYNOLO,@IF(METSTUPROG.PROGCODE - 1,'MDE','YD') AS EPIPEDO_SPOYDVN, 2009-METSTUPROG.AK+1 AS ETOS, SEX AS FYLO, PLTEXT AS XVRA
FROM MET,METSTUPROG,PLTAB
WHERE  MET.TMIMACODE = :1 AND METSTUPROG.AK IS NOT NULL
	AND METSTUPROG.AK <= 2009 AND MET.MITROO = METSTUPROG.MITROO
	AND METSTUPROG.MITROO NOT IN (SELECT MITROO FROM METDIAKOP WHERE DATEAPO<SYSDATE AND DATEEOS IS NULL 
	AND METDIAKOP.PROGCODE = METSTUPROG.PROGCODE AND TMIMACODE = :1)  AND SEX IS NOT NULL
	AND (METSTUPROG.DATEANAG IS NULL OR METSTUPROG.DATEANAG>SYSDATE)
	AND PLCOLUMN ='YPHK' AND MET.YPHK = PLTAB.PLCODE AND MET.YPHK != '0099'
GROUP BY 2,3,4,5 ORDER BY 2 DESC,3,4,5;

;====================================================================================================;
;ELEGXOS : ELEGXOYME POIOI FOITHTES DEN EXOUN KATAXVRHMENH YPHKOOTHTA KAI EXOUN XVRA GENNHSHS DIAFORH THS ELLHNIKHS;
;====================================================================================================;

SELECT COUNT(MET.MITROO) AS SYNOLO,@IF(METSTUPROG.PROGCODE - 1,'MDE','YD') AS EPIPEDO_SPOYDVN, 2009-METSTUPROG.AK+1 AS ETOS, SEX AS FYLO, PLTEXT AS XVRA
FROM MET,METSTUPROG,PLTAB
WHERE  MET.TMIMACODE = :1 AND METSTUPROG.AK IS NOT NULL
	AND METSTUPROG.AK <= 2009 AND MET.MITROO = METSTUPROG.MITROO
	AND METSTUPROG.MITROO NOT IN (SELECT MITROO FROM METDIAKOP WHERE DATEAPO<SYSDATE AND DATEEOS IS NULL 
	AND METDIAKOP.PROGCODE = METSTUPROG.PROGCODE AND TMIMACODE = :1)  AND SEX IS NOT NULL
	AND (METSTUPROG.DATEANAG IS NULL OR METSTUPROG.DATEANAG>SYSDATE) AND MET.YPHK IS NULL
	AND PLCOLUMN ='YPHK' AND MET.COORIG = PLTAB.PLCODE AND MET.COORIG != '0099'
GROUP BY 2,3,4,5 ORDER BY 2 DESC,3,4,5;



;====================================================================================================;
;FOITHTES ANA EPIPEDO SPOYDON (MDE - YD), ETOS SPOUDON, FYLO KAI XORA GENNHSHS.


;TO QUERY EXEI KAI MIA PARAMETRO POU PREPEI NA BALETE KAI EINAI O KODIKOS THS SXOLHS;
;====================================================================================================;

SELECT COUNT(MET.MITROO) AS SYNOLO,@IF(METSTUPROG.PROGCODE - 1,'MDE','YD') AS EPIPEDO_SPOYDVN, 2009-METSTUPROG.AK+1 AS ETOS, SEX AS FYLO, PLTEXT AS XVRA
FROM MET,METSTUPROG,PLTAB
WHERE  MET.TMIMACODE = :1 AND METSTUPROG.AK IS NOT NULL
	AND METSTUPROG.AK <= 2009 AND MET.MITROO = METSTUPROG.MITROO
	AND METSTUPROG.MITROO NOT IN (SELECT MITROO FROM METDIAKOP WHERE DATEAPO<SYSDATE AND DATEEOS IS NULL 
	AND METDIAKOP.PROGCODE = METSTUPROG.PROGCODE AND TMIMACODE = :1)  AND SEX IS NOT NULL
	AND (METSTUPROG.DATEANAG IS NULL OR METSTUPROG.DATEANAG>SYSDATE)
	AND PLCOLUMN ='YPHK' AND MET.COORIG = PLTAB.PLCODE AND MET.COORIG != '0099'
GROUP BY 2,3,4,5 ORDER BY 2 DESC,3,4,5;

