update pltab set pltext ='ейпа' where plcolumn = 'IDRYMA' and plcode='00041';
update pltab set pltext ='памепистглиоу патяым' where plcolumn = 'IDRYMA' and plcode='00042';
update pltab set pltext ='памепистглиоу иыаммимым' where plcolumn = 'IDRYMA' and plcode='00043';
update pltab set pltext ='памепистглиоу йягтгс' where plcolumn = 'IDRYMA' and plcode='00044';
update pltab set pltext ='тлглатос истояиас аяваиокоциас ейпа' where plcolumn = 'IDRYMA' and plcode='00045';
update pltab set pltext ='амытатгс свокгс йакым тевмым' where plcolumn = 'IDRYMA' and plcode='00046';
update pltab set pltext ='памтеиоу памепистглиоу йоимымийым йаи покитийым епистглым' where plcolumn = 'IDRYMA' and plcode='00123';
update pltab set pltext ='молийг ахгмас' where plcolumn = 'IDRYMA' and plcode='00124';
update pltab set pltext ='покитийос лгвамийос елп' where plcolumn = 'IDRYMA' and plcode='00201';
update pltab set pltext ='покитийос лгвамийос апх' where plcolumn = 'IDRYMA' and plcode='00203';
update pltab set pltext ='покитийос лгвамийос памепистглиоу патяым' where plcolumn = 'IDRYMA' and plcode='00205';
update pltab set pltext ='покитийос лгвамийос дглойяитеиоу памепистглиоу хяайгс' where plcolumn = 'IDRYMA' and plcode='00207';
update pltab set pltext ='покитийос лгвамийос памепистглиоу хессакиас' where plcolumn = 'IDRYMA' and plcode='00208';
update pltab set pltext ='лгвамокоцос лгвамийос елп' where plcolumn = 'IDRYMA' and plcode='00209';
update pltab set pltext ='лгвамокоцос лгвамийос апх' where plcolumn = 'IDRYMA' and plcode='00211';
update pltab set pltext ='лгвамокоцос лгвамийос памепистглиоу патяым' where plcolumn = 'IDRYMA' and plcode='00213';
update pltab set pltext ='тлглатос епистглгс упокоцистым памепистглиоу йягтгс' where plcolumn = 'IDRYMA' and plcode='00216';
update pltab set pltext ='гкейтяокоцос лгвамийос йаи лгвамийос упокоцистым елп' where plcolumn = 'IDRYMA' and plcode='00217';
update pltab set pltext ='гкейтяокоцос лгвамийос йаи лгвамийос упокоцистым апх' where plcolumn = 'IDRYMA' and plcode='00219';
update pltab set pltext ='тлглатос гкейтяокоцым лгвамийым йаи тевмокоциас упокоцистым памепистглиоу патяым' where plcolumn = 'IDRYMA' and plcode='00221';
update pltab set pltext ='гкейтяокоцос лгвамийос йаи лгвамийос упокоцистым дглойяитеиоу памепистглиоу хяайгс' where plcolumn = 'IDRYMA' and plcode='00223';
update pltab set pltext ='ацяомолос йаи топоцяажос лгвамийос елп' where plcolumn = 'IDRYMA' and plcode='00225';
update pltab set pltext ='ацяомолос йаи топоцяажос лгвамийос апх' where plcolumn = 'IDRYMA' and plcode='00227';
update pltab set pltext ='маупгцос лгвамокоцос лгвамийос елп' where plcolumn = 'IDRYMA' and plcode='00229';
update pltab set pltext ='лгвамийос паяацыцгс йаи диоийгсгс покутевмеиоу йягтгс' where plcolumn = 'IDRYMA' and plcode='00230';
update pltab set pltext ='аявитейтомас лгвамийос елп' where plcolumn = 'IDRYMA' and plcode='00231';
update pltab set pltext ='аявитейтомас лгвамийос апх' where plcolumn = 'IDRYMA' and plcode='00233';
update pltab set pltext ='вглийос лгвамийос елп' where plcolumn = 'IDRYMA' and plcode='00235';
update pltab set pltext ='вглийос лгвамийос апх' where plcolumn = 'IDRYMA' and plcode='00237';
update pltab set pltext ='вглийос лгвамийос памепистглиоу патяым' where plcolumn = 'IDRYMA' and plcode='00239';
update pltab set pltext ='лгвамийос летаккеиым летаккоуяцос елп' where plcolumn = 'IDRYMA' and plcode='00241';
update pltab set pltext ='лгвамийос ояуйтым пояым покутевмеиоу йягтгс' where plcolumn = 'IDRYMA' and plcode='00242';
update pltab set pltext ='лахглатийос ейпа' where plcolumn = 'IDRYMA' and plcode='00243';
update pltab set pltext ='лахглатийос апх' where plcolumn = 'IDRYMA' and plcode='00245';
update pltab set pltext ='лахглатийос памепистглиоу патяым' where plcolumn = 'IDRYMA' and plcode='00247';
update pltab set pltext ='лахглатийос памепистглиоу иыаммимым' where plcolumn = 'IDRYMA' and plcode='00249';
update pltab set pltext ='лахглатийос памепистглиоу йягтгс' where plcolumn = 'IDRYMA' and plcode='00251';
update pltab set pltext ='лахглатийос памепистглиоу аицаиоу' where plcolumn = 'IDRYMA' and plcode='00252';
update pltab set pltext ='жусийос ейпа' where plcolumn = 'IDRYMA' and plcode='00253';
update pltab set pltext ='жусийос апх' where plcolumn = 'IDRYMA' and plcode='00255';
update pltab set pltext ='жусийос памепистглиоу патяым' where plcolumn = 'IDRYMA' and plcode='00257';
update pltab set pltext ='жусийос памепистглиоу иыаммимым' where plcolumn = 'IDRYMA' and plcode='00259';
update pltab set pltext ='жусийос памепистглиоу йягтгс' where plcolumn = 'IDRYMA' and plcode='00261';
update pltab set pltext ='вглийос ейпа' where plcolumn = 'IDRYMA' and plcode='00263';
update pltab set pltext ='вглийос апх' where plcolumn = 'IDRYMA' and plcode='00265';
update pltab set pltext ='вглийос памепистглиоу патяым' where plcolumn = 'IDRYMA' and plcode='00267';
update pltab set pltext ='вглийос памепистглиоу иыаммимым' where plcolumn = 'IDRYMA' and plcode='00269';
update pltab set pltext ='вглийос памепистглиоу йягтгс' where plcolumn = 'IDRYMA' and plcode='00270';
update pltab set pltext ='тлглатос пеяибаккомтос памепистглиоу аицаиоу' where plcolumn = 'IDRYMA' and plcode='00276';
update pltab set pltext ='биокоцос ейпа' where plcolumn = 'IDRYMA' and plcode='00277';
update pltab set pltext ='биокоцос апх' where plcolumn = 'IDRYMA' and plcode='00279';
update pltab set pltext ='биокоцос памепистглиоу патяым' where plcolumn = 'IDRYMA' and plcode='00281';
update pltab set pltext ='цеыкоцос ейпа' where plcolumn = 'IDRYMA' and plcode='00283';
update pltab set pltext ='цеыкоцос апх' where plcolumn = 'IDRYMA' and plcode='00285';
update pltab set pltext ='цеыкоцос памепистглиоу патяым' where plcolumn = 'IDRYMA' and plcode='00287';
update pltab set pltext ='тлглатос иатяийгс ейпа' where plcolumn = 'IDRYMA' and plcode='00295';
update pltab set pltext ='тлглатос иатяийгс апх' where plcolumn = 'IDRYMA' and plcode='00297';
update pltab set pltext ='тлглатос одомтиатяийгс ейпа' where plcolumn = 'IDRYMA' and plcode='00303';
update pltab set pltext ='тлглатос оийомолийым епистглым апх' where plcolumn = 'IDRYMA' and plcode='00311';
update pltab set pltext ='тлглатос статистийгс йаи асжакистийгс епистглгс памепистглиоу пеияаиа' where plcolumn = 'IDRYMA' and plcode='00318';
update pltab set pltext ='тлглатос жутийгс паяацыцгс цпа' where plcolumn = 'IDRYMA' and plcode='00323';
update pltab set pltext ='цеыпомийоу памепистглиоу ахгмым' where plcolumn = 'IDRYMA' and plcode='00325';
update pltab set pltext ='тлглатос статистийгс опа' where plcolumn = 'IDRYMA' and plcode='00329';
update pltab set pltext ='тлглатос пкгяожояийгс йаи тгкепийоимымиым ейпа' where plcolumn = 'IDRYMA' and plcode='00330';
update pltab set pltext ='гкейтяокоцос лгвамийос йаи лгвамийос упокоцистым покутевмеиоу йягтгс' where plcolumn = 'IDRYMA' and plcode='00331';
update pltab set pltext ='лгвамокоцос лгвамийос биолгвамиас памепистглиоу хессакиас' where plcolumn = 'IDRYMA' and plcode='00332';
update pltab set pltext ='тлглатос ежаялослемгс пкгяожояийгс памепистглиоу лайедомиас оийомолийым йаи йоимымийым епистглым' where plcolumn = 'IDRYMA' and plcode='00335';
update pltab set pltext ='тлглатос пкгяожояийгс апх' where plcolumn = 'IDRYMA' and plcode='00338';
update pltab set pltext ='тлглатос пкгяожояийгс памепистглиоу пеияаиа' where plcolumn = 'IDRYMA' and plcode='00339';
update pltab set pltext ='тлглатос пкгяожояийгс памепистглиоу иыаммимым' where plcolumn = 'IDRYMA' and plcode='00340';
update pltab set pltext ='тлглатос цеыцяажиас памепистглиоу аицаиоу' where plcolumn = 'IDRYMA' and plcode='04298';
update pltab set pltext ='тлглатос жикосожиас паидацыцийгс йаи ьувокоциас памепистглиоу иыаммимым' where plcolumn = 'IDRYMA' and plcode='E4000';