CONNECT databasename SYSADM/sysadmpassword;
UNLOAD DATABASE databasename.ULD ON SERVER;
DISCONNECT 1;
SET SERVER SERVER1;
DROP DATABASE databasename;
CREATE DATABASE databasename;
SET SERVER OFF;
CONNECT databasename SYSADM/SYSADM;
SET RECOVERY OFF;
SET ERRORLEVEL 3;
LOCK DATABASE;
LOAD SQL C:\COMMON\BACKUP\base_.uld ON SERVER ;
COMMIT;
UPDATE STATISTICS ON DATABASE;
UNLOCK DATABASE;
SET RECOVERY ON;
EXIT;

