Create Table METCOURSE_HELP ( COURCODE INTEGER NOT NULL, TMIMACODE INTEGER NOT NULL, UNIVCODE INTEGER NOT NULL, TMIMACODEPAR INTEGER ,
 TITLOS VARCHAR (254)  , PERIOD VARCHAR (2)  , KRG VARCHAR (1)  , E_K INTEGER , MAXFOIT INTEGER , VR_UPAR INTEGER , VR_APAR INTEGER , VR_EPAR INTEGER ,
 PRAKPAR INTEGER , AK INTEGER NOT NULL, MONADES REAL , TOMCODEPAR INTEGER  ) ;
Create Table METPROSPU_HELP ( PROGCODE INTEGER NOT NULL, COURCODE INTEGER NOT NULL, AK INTEGER NOT NULL, PERIOD VARCHAR (2)  ,
 TMIMACODE INTEGER NOT NULL, KAT VARCHAR (2)  NOT NULL, EIDOSMA VARCHAR (2)   ) ;
Create Table METDEPMA_HELP ( COURCODE INTEGER NOT NULL, AM_DEP INTEGER NOT NULL, AK INTEGER NOT NULL );

INSERT INTO METCOURSE_HELP (COURCODE,TMIMACODE,UNIVCODE,TMIMACODEPAR,TITLOS,PERIOD,KRG,E_K,MAXFOIT,VR_UPAR,VR_APAR,VR_EPAR,PRAKPAR,AK,MONADES,TOMCODEPAR)
SELECT COURCODE,TMIMACODE,UNIVCODE,TMIMACODEPAR,TITLOS,PERIOD,KRG,E_K,MAXFOIT,VR_UPAR,VR_APAR,VR_EPAR,PRAKPAR,AK,MONADES,TOMCODEPAR 
FROM METCOURSE WHERE AK = 2006;
INSERT INTO METPROSPU_HELP ( PROGCODE,COURCODE,AK,PERIOD,TMIMACODE,KAT,EIDOSMA)
SELECT  PROGCODE,COURCODE,AK,PERIOD,TMIMACODE,KAT,EIDOSMA FROM METPROSPU WHERE AK = 2006;
INSERT INTO METDEPMA_HELP  (COURCODE,AM_DEP,AK)
SELECT  COURCODE,AM_DEP,AK FROM METDEPMA WHERE AK = 2006;

UPDATE METCOURSE_HELP SET AK = 2007;
UPDATE METPROSPU_HELP SET AK = 2007;
UPDATE METDEPMA_HELP SET AK = 2007;

INSERT INTO METCOURSE (COURCODE,TMIMACODE,UNIVCODE,TMIMACODEPAR,TITLOS,PERIOD,KRG,E_K,MAXFOIT,VR_UPAR,VR_APAR,VR_EPAR,PRAKPAR,AK,MONADES,TOMCODEPAR)
SELECT COURCODE,TMIMACODE,UNIVCODE,TMIMACODEPAR,TITLOS,PERIOD,KRG,E_K,MAXFOIT,VR_UPAR,VR_APAR,VR_EPAR,PRAKPAR,AK,MONADES,TOMCODEPAR
FROM METCOURSE_HELP WHERE COURCODE||AK NOT IN (SELECT COURCODE||AK FROM METCOURSE );

INSERT INTO METPROSPU (PROGCODE,COURCODE,AK,PERIOD,TMIMACODE,KAT,EIDOSMA)
SELECT PROGCODE,COURCODE,AK,PERIOD,TMIMACODE,KAT,EIDOSMA 
FROM METPROSPU_HELP WHERE COURCODE||AK||KAT||PERIOD||PROGCODE||TMIMACODE  NOT IN (SELECT COURCODE||AK||KAT||PERIOD||PROGCODE||TMIMACODE  FROM METPROSPU );

INSERT INTO METDEPMA (COURCODE,AM_DEP,AK)
SELECT COURCODE,AM_DEP,AK FROM METDEPMA_HELP WHERE AM_DEP||COURCODE||AK NOT IN (SELECT AM_DEP||COURCODE||AK FROM METDEPMA );

DROP TABLE METCOURSE_HELP;
DROP TABLE METPROSPU_HELP;
DROP TABLE METDEPMA_HELP;
 

