delete from ypcourse where ak = 2005;
delete from ypxomada where ak = 2005;
delete from proairet where ak = 2005;
delete from proapet where ak = 2005;
delete from metab where ak = 2005;
delete from omadaepi where ak = 2005;
delete from omadepim where ak = 2005;
delete from sygxvn where ak = 2005;
delete from ypmadepi where ak = 2005;
delete from ypmadepm where ak = 2005;
delete from lang where ak = 2005;
delete from st_m where ak = 2005;
delete from depma where ak = 2005;
delete from OMADAEPI6 where ak = 2005;
delete from OMADEPIM6 where ak = 2005;

a;
Create Table YPCOURSE_HELP ( K_TM INTEGER NOT NULL, KAT VARCHAR (2)  NOT NULL, EJ VARCHAR (2)  NOT NULL, K_M INTEGER NOT NULL, OMADA VARCHAR (4)  , 
AK INTEGER NOT NULL );
Create Table YPXOMADA_HELP ( K_TM INTEGER NOT NULL, OMADA VARCHAR (4)  NOT NULL, EJ VARCHAR (2)  NOT NULL, MAXCHOICE INTEGER , AK INTEGER  , KAT VARCHAR (2) ) ;
Create Table OMADAEPI_HELP ( K_TM INTEGER NOT NULL, KAT VARCHAR (2)  NOT NULL, EJ VARCHAR (2)  NOT NULL, K_M INTEGER NOT NULL, OMADAEPI VARCHAR (4)  ,
 AK INTEGER NOT NULL ) ;
Create Table OMADEPIM_HELP ( K_TM INTEGER NOT NULL, EJ VARCHAR (2)  NOT NULL, OMADAEPI VARCHAR (4)  NOT NULL, MAXCHOICE INTEGER , AK INTEGER ,
 KAT VARCHAR (2)   );
Create Table PROAIRET_HELP ( K_TM INTEGER NOT NULL, KAT VARCHAR (2)  NOT NULL, EJ VARCHAR (2)  NOT NULL, K_M INTEGER NOT NULL, AK INTEGER NOT NULL ) ;
Create Table SYGXVN_HELP ( K_M INTEGER NOT NULL, AK INTEGER NOT NULL, K_MOLD INTEGER NOT NULL, K_TM INTEGER NOT NULL, AKOLD INTEGER  );
Create Table YPMADEPI_HELP ( K_TM INTEGER NOT NULL, EJ VARCHAR (2)  NOT NULL, YPEROMADA VARCHAR (4)  NOT NULL, OMADAEPI VARCHAR (4)  NOT NULL, 
AK INTEGER NOT NULL, KAT VARCHAR (2)  NOT NULL );
Create Table YPMADEPM_HELP ( K_TM INTEGER NOT NULL, EJ VARCHAR (2)  NOT NULL, YPEROMADA VARCHAR (4)  NOT NULL, MAXCHOICE INTEGER , 
KAT VARCHAR (2)  NOT NULL, AK INTEGER NOT NULL );
Create Table LANG_HELP ( K_TM INTEGER NOT NULL, KAT VARCHAR (2)  NOT NULL, EJ VARCHAR (2)  NOT NULL, K_M INTEGER NOT NULL, OMADA VARCHAR (4)  , 
AK INTEGER NOT NULL );
Create Table ST_M_HELP ( K_M INTEGER NOT NULL, K_TMPAR INTEGER , K_TM INTEGER , K_TOMPAR INTEGER , TITLOS VARCHAR (100)  , XU VARCHAR (1)  , KRG VARCHAR (1)  , 
E_K INTEGER , MAXFOIT INTEGER , VR_UPAR INTEGER , VR_APAR INTEGER , VR_EPAR INTEGER , PRAKPAR INTEGER , AK INTEGER , MONADES FLOAT , SEQ INTEGER  ) ;
Create Table DEPMA_HELP ( K_M INTEGER NOT NULL, AM_DEP INTEGER NOT NULL, AK INTEGER , AA INTEGER  ) ;
Create Table PROAPET_HELP ( K_M INTEGER NOT NULL, GROUPNO VARCHAR (2)  NOT NULL, K_MPRO INTEGER NOT NULL, AK INTEGER  ) ;
Create Table METAB_HELP ( K_TM INTEGER NOT NULL, K_M INTEGER NOT NULL, AK INTEGER NOT NULL, EJ VARCHAR (2)  NOT NULL, TYPOS VARCHAR (2)  , 
OMADA VARCHAR (4)  , XU VARCHAR (1)   ) ;
Create Table OMADAEPI6_HELP ( K_TM INTEGER NOT NULL, KAT VARCHAR (2)  NOT NULL, EJ VARCHAR (2)  NOT NULL, K_M INTEGER NOT NULL, OMADAEPI VARCHAR (4)  , 
AK INTEGER NOT NULL ) ;
Create Table OMADEPIM6_HELP ( K_TM INTEGER NOT NULL, OMADAEPI VARCHAR (4)  NOT NULL, MAXCHOICE INTEGER , AK INTEGER , KAT VARCHAR (2)   ) ;
a;
INSERT INTO YPCOURSE_HELP SELECT * FROM YPCOURSE WHERE AK = 2004;
INSERT INTO YPXOMADA_HELP SELECT * FROM YPXOMADA WHERE AK = 2004;
INSERT INTO OMADAEPI_HELP SELECT * FROM OMADAEPI WHERE AK = 2004;
INSERT INTO OMADEPIM_HELP SELECT * FROM OMADEPIM WHERE AK = 2004;
INSERT INTO PROAIRET_HELP SELECT * FROM PROAIRET WHERE AK = 2004;
INSERT INTO SYGXVN_HELP SELECT * FROM SYGXVN WHERE AK = 2004;
INSERT INTO YPMADEPM_HELP SELECT * FROM YPMADEPM WHERE AK = 2004;
INSERT INTO YPMADEPI_HELP SELECT * FROM YPMADEPI WHERE AK = 2004;
INSERT INTO LANG_HELP SELECT * FROM LANG WHERE AK = 2004;
INSERT INTO ST_M_HELP SELECT * FROM ST_M WHERE AK = 2004;
INSERT INTO DEPMA_HELP SELECT * FROM DEPMA WHERE AK = 2004;
INSERT INTO PROAPET_HELP SELECT * FROM PROAPET WHERE AK = 2004;
INSERT INTO METAB_HELP SELECT * FROM METAB WHERE AK = 2004;
INSERT INTO OMADAEPI6_HELP SELECT * FROM OMADAEPI6 WHERE AK = 2004;
INSERT INTO OMADEPIM6_HELP SELECT * FROM OMADEPIM6 WHERE AK = 2004;

a;
UPDATE YPCOURSE_HELP SET AK = 2005;
UPDATE YPXOMADA_HELP SET AK = 2005;
UPDATE OMADAEPI_HELP SET AK = 2005;
UPDATE OMADEPIM_HELP SET AK = 2005;
UPDATE PROAIRET_HELP SET AK = 2005;
UPDATE SYGXVN_HELP SET AK = 2005;
UPDATE YPMADEPM_HELP SET AK = 2005;
UPDATE YPMADEPI_HELP SET AK = 2005;
UPDATE LANG_HELP SET AK = 2005;
UPDATE ST_M_HELP SET AK = 2005;
UPDATE DEPMA_HELP SET AK = 2005;
UPDATE PROAPET_HELP SET AK = 2005;
UPDATE METAB_HELP SET AK = 2005;
UPDATE OMADAEPI6_HELP SET AK = 2005;
UPDATE OMADEPIM6_HELP SET AK = 2005;

a;

INSERT INTO YPCOURSE SELECT * FROM YPCOURSE_HELP WHERE K_M||AK||KAT||EJ  NOT IN (SELECT K_M||AK||KAT||EJ  FROM YPCOURSE WHERE AK = 2005);
INSERT INTO YPXOMADA SELECT * FROM YPXOMADA_HELP WHERE OMADA||AK||KAT||EJ  NOT IN (SELECT OMADA||AK||KAT||EJ  FROM YPXOMADA WHERE AK=2005 );
INSERT INTO OMADAEPI SELECT * FROM OMADAEPI_HELP WHERE OMADAEPI||K_M||AK||EJ||KAT||K_TM  NOT IN (SELECT OMADAEPI||K_M||AK||KAT||EJ||K_TM  FROM OMADAEPI WHERE AK=2005 );
INSERT INTO OMADEPIM SELECT * FROM OMADEPIM_HELP WHERE OMADAEPI||KAT||AK||EJ||K_TM NOT IN (SELECT OMADAEPI||KAT||AK||EJ||K_TM FROM OMADEPIM WHERE AK=2005 );
INSERT INTO PROAIRET SELECT * FROM PROAIRET_HELP WHERE K_M||AK||KAT||EJ  NOT IN (SELECT K_M||AK||KAT||EJ  FROM PROAIRET WHERE AK=2005);
INSERT INTO SYGXVN SELECT * FROM SYGXVN_HELP WHERE K_M||AK||K_MOLD||K_TM||AKOLD  NOT IN (SELECT K_M||AK||AKOLD||K_MOLD||K_TM  FROM SYGXVN WHERE AK=2005);
INSERT INTO YPMADEPM SELECT * FROM YPMADEPM_HELP WHERE YPEROMADA||KAT||AK||EJ  NOT IN (SELECT YPEROMADA||KAT||AK||EJ  FROM YPMADEPM WHERE AK=2005);
INSERT INTO YPMADEPI SELECT * FROM YPMADEPI_HELP WHERE OMADAEPI||AK||KAT||YPEROMADA||EJ  NOT IN (SELECT OMADAEPI||AK||KAT||YPEROMADA||EJ  FROM YPMADEPI WHERE AK=2005);
INSERT INTO LANG SELECT * FROM LANG_HELP WHERE K_M||AK||EJ||KAT||K_TM  NOT IN (SELECT K_M||AK||EJ||KAT||K_TM  FROM LANG WHERE AK=2005);
INSERT INTO ST_M SELECT * FROM ST_M_HELP WHERE K_M||AK NOT IN (SELECT K_M||AK FROM ST_M WHERE AK=2005);
INSERT INTO DEPMA SELECT * FROM DEPMA_HELP WHERE K_M||AK||AM_DEP  NOT IN (SELECT K_M||AK||AM_DEP  FROM DEPMA WHERE AK=2005);
INSERT INTO PROAPET SELECT * FROM PROAPET_HELP WHERE K_M||K_MPRO||AK||GROUPNO  NOT IN (SELECT K_M||K_MPRO||AK||GROUPNO  FROM PROAPET WHERE AK=2005);
INSERT INTO METAB SELECT * FROM METAB_HELP WHERE K_M||AK||EJ||XU  NOT IN (SELECT K_M||AK||EJ||XU  FROM METAB WHERE AK=2005);
INSERT INTO OMADAEPI6 SELECT * FROM OMADAEPI6_HELP WHERE OMADAEPI||K_M||AK||EJ||KAT||K_TM  NOT IN (SELECT OMADAEPI||K_M||AK||EJ||KAT||K_TM  FROM OMADAEPI6 WHERE AK=2005 );
INSERT INTO OMADEPIM6 SELECT * FROM OMADEPIM6_HELP WHERE OMADAEPI||KAT||AK||K_TM  NOT IN (SELECT OMADAEPI||KAT||AK||K_TM  FROM OMADEPIM6 WHERE AK=2005 );


a;
DROP TABLE YPCOURSE_HELP;
DROP TABLE YPXOMADA_HELP;
DROP TABLE OMADAEPI_HELP;
DROP TABLE OMADEPIM_HELP;
DROP TABLE PROAIRET_HELP;
DROP TABLE SYGXVN_HELP;
DROP TABLE YPMADEPM_HELP;
DROP TABLE YPMADEPI_HELP;
DROP TABLE LANG_HELP;
DROP TABLE ST_M_HELP;
DROP TABLE DEPMA_HELP;
DROP TABLE PROAPET_HELP;
DROP TABLE METAB_HELP;
DROP TABLE OMADAEPI6_HELP;
DROP TABLE OMADEPIM6_HELP;

a;

SELECT COUNT(*) FROM YPCOURSE WHERE AK = 2005;
94;
SELECT COUNT(*) FROM YPXOMADA WHERE AK = 2005;
2;
SELECT COUNT(*) FROM OMADAEPI WHERE AK = 2005;
129;
SELECT COUNT(*)  FROM OMADEPIM WHERE AK = 2005;
29;
SELECT COUNT(*) FROM PROAIRET WHERE AK = 2005;
0;
SELECT COUNT(*) FROM SYGXVN WHERE AK = 2005;
8;
SELECT COUNT(*) FROM YPMADEPM WHERE AK = 2005;
6;
SELECT COUNT(*)  FROM YPMADEPI WHERE AK = 2005;
11;
SELECT COUNT(*) FROM LANG WHERE AK = 2005;
16;
SELECT COUNT(*) FROM ST_M WHERE AK = 2005;
139;
SELECT COUNT(*) FROM DEPMA WHERE AK = 2005;
200;
SELECT COUNT(*) FROM PROAPET WHERE AK = 2005;
0;
SELECT COUNT(*) FROM METAB WHERE AK = 2005;
7;
SELECT COUNT(*) FROM OMADAEPI6 WHERE AK = 2005;
7;
SELECT COUNT(*) FROM OMADEPIM6 WHERE AK = 2005;
7;