CREATE TABLE FOIT (STATUS VARCHAR(15),K_TM INTEGER,K_TMTEXT VARCHAR(50),K_F VARCHAR(8),SEX VARCHAR(1),YPHK VARCHAR(10), YPHKTEXT VARCHAR(100),BIRTHDATE DATE,
COORIG VARCHAR(10), COORIGTEXT VARCHAR(100),NOMOSMHTR VARCHAR(10),NOMOSMHTRTEXT VARCHAR(100),POLIMHTR VARCHAR(10), POLIMHTRTEXT VARCHAR(100), 
DIMOTOLOGIO VARCHAR(20), DIMOTOLOGIOTEXT VARCHAR (100), AK INTEGER,EJ VARCHAR(10), EJTEXT VARCHAR(100), H_EGR DATE,TROPOS VARCHAR(10),TROPOSTEXT VARCHAR(100), 
COKAT VARCHAR(10), COKATTEXT VARCHAR(100),NOMOSKAT VARCHAR(10), NOMOSKATTEXT VARCHAR(100), POLIKAT VARCHAR(10), POLIKATTEXT VARCHAR(100), SIRA INTEGER,MONADES FLOAT,
LYKIO VARCHAR(60),ETOSAPOF INTEGER,APOLYTIRIO VARCHAR(8),DATEDEL DATE,PERIOD VARCHAR(25),DATEEJET DATE,ETOSAPOFPOL INTEGER, GRADEAPOF FLOAT);


INSERT INTO FOIT  SELECT 'емеяцос',K_TM,NULL,K_F,SEX,YPHK,NULL,BIRTHDATE,COORIG,NULL,NOMOSMHTR,NULL,POLIMHTR, NULL,DIMOTOLOGIO,NULL,AK,EJ,NULL,H_EGR,TROPOS,NULL,COKAT,NULL,NOMOSKAT,NULL,POLIKAT,NULL,
SIRA,MONADES,LYKIO,ETOSAPOF,APOLYTIRIO,NULL,NULL,NULL,NULL,NULL
FROM ST_F WHERE ST_F.AK BETWEEN 1992 AND 2004 AND ST_F.K_F IN (SELECT K_F FROM EGRAFI) AND ST_F.K_F NOT IN (SELECT K_F FROM HST_F) AND ST_F.K_F NOT IN (SELECT K_F FROM DIAGRAFENTES)  
AND ST_F.K_F NOT IN (SELECT K_F FROM APOFOIT);


INSERT INTO FOIT  SELECT 'амацояеулемос',K_TM,NULL,K_F,SEX,YPHK,NULL,BIRTHDATE,COORIG,NULL,NOMOSMHTR,NULL,POLIMHTR, NULL,DIMOTOLOGIO,NULL,AK,EJ,NULL,H_EGR,TROPOS,NULL,COKAT,NULL,NOMOSKAT,NULL,POLIKAT,NULL,
SIRA,MONADES,LYKIO,ETOSAPOF,APOLYTIRIO,NULL,PERIOD,DATEEJET,ETOSAPOFPOL,GRADEAPOF
FROM HST_F WHERE HST_F.AK BETWEEN 1992 AND 2004;


INSERT INTO FOIT  SELECT 'диацяажемтас',K_TM,NULL,ST_F.K_F,SEX,YPHK,NULL,BIRTHDATE,COORIG,NULL,NOMOSMHTR,NULL,POLIMHTR, NULL,DIMOTOLOGIO,NULL,ST_F.AK,ST_F.EJ,NULL,H_EGR,TROPOS,NULL,COKAT,NULL,NOMOSKAT,NULL,POLIKAT,NULL,
SIRA,MONADES,LYKIO,ETOSAPOF,APOLYTIRIO,H,NULL,NULL,NULL,NULL
FROM ST_F,DIAGRAFENTES WHERE ST_F.AK BETWEEN 1992 AND 2004 AND ST_F.K_F IN (SELECT K_F FROM EGRAFI) AND ST_F.K_F NOT IN (SELECT K_F FROM HST_F) AND ST_F.K_F=DIAGRAFENTES.K_F;


INSERT INTO FOIT  SELECT 'апожоитгяио',ST_F.K_TM,NULL,ST_F.K_F,SEX,YPHK,NULL,BIRTHDATE,COORIG,NULL,NOMOSMHTR,NULL,POLIMHTR, NULL,DIMOTOLOGIO,NULL,ST_F.AK,ST_F.EJ,NULL,H_EGR,TROPOS,NULL,COKAT,NULL,NOMOSKAT,NULL,POLIKAT,NULL,
SIRA,MONADES,LYKIO,ETOSAPOF,APOLYTIRIO,H,NULL,NULL,NULL,NULL
FROM ST_F,APOFOIT WHERE ST_F.AK BETWEEN 1992 AND 2004 AND ST_F.K_F IN (SELECT K_F FROM EGRAFI) AND ST_F.K_F NOT IN (SELECT K_F FROM HST_F) AND ST_F.K_F=APOFOIT.K_F;


UPDATE FOIT SET K_TMTEXT = (SELECT TITLOS FROM TMHMA WHERE FOIT.K_TM=TMHMA.K_TM);

UPDATE FOIT SET YPHKTEXT = (SELECT PLTEXT FROM PLTAB WHERE PLCOLUMN = 'YPHK' AND PLCODE = YPHK) WHERE YPHK IS NOT NULL AND YPHK != ' ' AND YPHK != '  ' AND YPHK != '   ' AND YPHK != '    ';

UPDATE FOIT SET COORIGTEXT = (SELECT PLTEXT FROM PLTAB WHERE PLCOLUMN = 'YPHK' AND PLCODE = COORIG) WHERE COORIG IS NOT NULL  AND COORIG != ' ' AND COORIG != '  ' AND COORIG != '   ' AND COORIG != '    ';

UPDATE FOIT SET NOMOSMHTRTEXT = (SELECT PLTEXT FROM PLTAB WHERE PLCOLUMN = 'NOMOI'  AND PLCODE = NOMOSMHTR) WHERE NOMOSMHTR IS NOT NULL AND NOMOSMHTR != ' ' AND NOMOSMHTR != '  ' AND NOMOSMHTR != '   ' AND NOMOSMHTR != '    ' ;

UPDATE FOIT SET POLIMHTRTEXT = (SELECT PLTEXT FROM PLTAB WHERE PLCOLUMN = 'DHMOI'  AND PLCODE = POLIMHTR) WHERE POLIMHTR IS NOT NULL  AND POLIMHTR != ' ' AND POLIMHTR != '  ' AND POLIMHTR != '   ' AND POLIMHTR != '    ';

UPDATE FOIT SET DIMOTOLOGIOTEXT = (SELECT PLTEXT FROM PLTAB WHERE PLCOLUMN = 'DHMOI'  AND PLCODE = DIMOTOLOGIO) WHERE DIMOTOLOGIO IS NOT NULL  AND DIMOTOLOGIO != ' ' AND DIMOTOLOGIO != '  ' AND DIMOTOLOGIO != '   ' AND DIMOTOLOGIO != '    ';

UPDATE FOIT SET EJTEXT = (SELECT PLTEXT FROM PLTAB WHERE PLCOLUMN = 'SEM' AND PLCODE = EJ) WHERE EJ IS NOT NULL AND EJ != ' ' AND EJ != '  ' AND EJ != '   ' AND EJ != '    ';

UPDATE FOIT SET TROPOSTEXT = (SELECT PLTEXT FROM PLTAB WHERE PLCOLUMN = 'TROPOS' AND PLCODE = TROPOS) WHERE TROPOS IS NOT NULL AND TROPOS != ' ' AND TROPOS != '  ' AND TROPOS != '   ' AND TROPOS != '    ';

UPDATE FOIT SET COKATTEXT = (SELECT PLTEXT FROM PLTAB WHERE PLCOLUMN = 'YPHK' AND PLCODE = COKAT) WHERE COKAT IS NOT NULL AND COKAT != ' ' AND COKAT != '  ' AND COKAT != '   ' AND COKAT != '    ';

UPDATE FOIT SET NOMOSKATTEXT = (SELECT PLTEXT FROM PLTAB WHERE PLCOLUMN = 'NOMOI' AND PLCODE = NOMOSKAT) WHERE NOMOSKAT IS NOT NULL AND NOMOSKAT != ' ' AND NOMOSKAT != '  ' AND NOMOSKAT != '   '  AND NOMOSKAT != '    ';

UPDATE FOIT SET POLIKATTEXT = (SELECT PLTEXT FROM PLTAB WHERE PLCOLUMN = 'POLI' AND PLCODE = POLIKAT) WHERE POLIKAT IS NOT NULL AND POLIKAT != ' ' AND POLIKAT != '  ' AND POLIKAT != '   ' AND POLIKAT != '    ';

FIRST UPDATE ACCESS IN FILE "Students_1992-2004";

DROP TABLE FOIT;






